### PR TITLE
Allow reconnects after disconnection

### PR DESCRIPTION
**Pull request by danielfone**
This allows shared links to remain valid, since if the network disconnects for a short period of time, the user can reconnect with the same session ID and key.

### CODE REVIEW

**Comment by danielfone** [comment]
@parndt this should close #5 . You can test this branch at the URL above (https://allow-reconnects.private-passage-37g.pages.dev/) and simulate the failure by generating a link, then disconnecting from the network for 15 seconds. Feedback welcome!

**Comment by parndt** [comment]
@danielfone works like a charm as far as I can tell 👍 👍 🥇

**Review by parndt — APPROVED** [review]
does what it says on the tin!

**Comment by parndt** [comment]
For context my test browser was 
image

**Pull request merged**
